name: repo2docker CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install repo2docker
        run: |
          python -m pip install --upgrade pip
          # Explicitly adding `six` as a workaround for https://github.com/docker/docker-py/pull/2844
          # Explicitly adding `chardet` as a workaround for https://github.com/jupyterhub/repo2docker/issues/1065
          python -m pip install jupyter-repo2docker six chardet

      - name: Build dask-tutorial Docker image
        run: jupyter-repo2docker --no-run --debug .
